version: '3.7'

services:
  cra-pake-helem:
    container_name: cra-pake-helem
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000