FROM node:14.15.3-alpine3.12 as build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent

COPY . ./

RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

COPY start.sh ./
COPY server/index.js ./server.js

# RUN apk update && apk add nodejs && apk add npm

RUN ["chmod", "+x", "start.sh"]
ENTRYPOINT ["sh", "./start.sh"]